name: Hello, World

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello, world
        run: echo "Hello, world"
